# syntax=docker/dockerfile:1
FROM python:3.13-slim

# Install uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /usr/local/bin/

WORKDIR /app

# Copy dependency manifests first for layer caching
COPY pyproject.toml uv.lock ./

# Install production dependencies only (no dev extras)
RUN uv sync --frozen --no-dev

# Copy application source
COPY src/ ./src/

# Copy serving-layer data artifacts
# These are generated by the pipeline and must exist before building the image.
# data/enriched/ and data/scores/ hold the parquet data.
# models/ holds the serialized .joblib files and metrics.json.
COPY data/enriched/ ./data/enriched/
COPY data/scores/ ./data/scores/
COPY models/ ./models/
COPY static/ ./static/

EXPOSE 8000

# Run as non-root user for security
RUN useradd --create-home appuser
USER appuser

CMD ["uv", "run", "zoneto", "serve", "--host", "0.0.0.0", "--port", "8000"]
