# syntax=docker/dockerfile:1
FROM python:3.13-slim

# Install uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /usr/local/bin/

WORKDIR /app

# Copy dependency manifests first for layer caching
COPY pyproject.toml uv.lock ./

# Install production dependencies only (no dev extras)
RUN uv sync --frozen --no-dev

# Pre-download sentence-transformer model weights so the container starts
# without any network access.  The model is ~120 MB and goes into the
# HuggingFace cache inside the image (~/.cache/huggingface).
# TRANSFORMERS_OFFLINE=1 at runtime prevents any accidental re-download.
RUN uv run python -c "from sentence_transformers import SentenceTransformer; SentenceTransformer('BAAI/bge-small-en-v1.5')"
ENV TRANSFORMERS_OFFLINE=1
ENV HF_DATASETS_OFFLINE=1

# Copy application source
COPY src/ ./src/

# Copy serving-layer data artifacts
# These are generated by the pipeline and must exist before building the image.
# data/enriched/ and data/scores/ hold the parquet data.
# models/ holds the serialized .joblib files and metrics.json.
# data/bylaw_index/ holds chunks.parquet + embeddings.npy (run `just bylaw-index` first).
COPY data/enriched/ ./data/enriched/
COPY data/scores/ ./data/scores/
COPY models/ ./models/
COPY static/ ./static/
# bylaw_index is optional — omit the COPY if it hasn't been built yet
COPY data/bylaw_index/ ./data/bylaw_index/

# ANTHROPIC_API_KEY must be supplied at runtime via --env; never bake it in.

EXPOSE 8000

# Run as non-root user for security
RUN useradd --create-home appuser
USER appuser

CMD ["uv", "run", "zoneto", "serve", "--host", "0.0.0.0", "--port", "8000"]
